"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("actors", [
      {
        id: 1,
        movie_id: 1,
        name: "Tom Holland",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Tom_Holland_by_Gage_Skidmore.jpg/640px-Tom_Holland_by_Gage_Skidmore.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        movie_id: 1,
        name: "Zendaya",
        photo:
          "https://static.republika.co.id/uploads/images/inpicture_slide/zendaya-_180815133142-761.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        movie_id: 1,
        name: "Benedict Cumberbacth",
        photo:
          "https://static.republika.co.id/uploads/images/inpicture_slide/zendaya-_180815133142-761.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        movie_id: 1,
        name: "Jacob Batalon",
        photo: "http://image.tmdb.org/t/p/w185/53YhaL4xw4Sb1ssoHkeSSBaO29c.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        movie_id: 1,
        name: "Jamie Foxx",
        photo: "http://image.tmdb.org/t/p/w185/hPwCMEq6jLAidsXAX5BfoYgIfg2.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        movie_id: 1,
        name: "Willem Dafoe",
        photo: "http://image.tmdb.org/t/p/w185/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        movie_id: 1,
        name: "Alfred Molina",
        photo: "http://image.tmdb.org/t/p/w185/nJo91Czesn6z0d0pkfbDoVZY3sg.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        movie_id: 1,
        name: "Benedict Wong",
        photo: "http://image.tmdb.org/t/p/w185/ukmfsl59Isvn9odgzMWBidA3cmt.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        movie_id: 2,
        name: "Stephanie Beatriz",
        photo: "http://image.tmdb.org/t/p/w185/7gNPOlsVIdg7QQOv1gRfHjv1Sdb.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        movie_id: 2,
        name: "María Cecilia Botero",
        photo: "http://image.tmdb.org/t/p/w185/nH6eBBgv1PI9J6Ftkn01ny1TMt1.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 11,
        movie_id: 2,
        name: "John Leguizamo",
        photo: "http://image.tmdb.org/t/p/w185/kEbXDtcPJ46GEhj5QlCTLZS6PWE.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 12,
        movie_id: 2,
        name: "Mauro Castillo",
        photo: "/qGNGBRyy9LumdFw32M7elnHP4IJ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 13,
        movie_id: 2,
        name: "Jessica Darrow",
        photo: "http://image.tmdb.org/t/p/w185/rJojc1ZUasEnUxSk7lL42RxyQbP.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 14,
        movie_id: 2,
        name: "Angie Cepeda",
        photo: "http://image.tmdb.org/t/p/w185/57OE4acJypRTey5OQlQjkpv14pQ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 15,
        movie_id: 2,
        name: "Carolina Gaitán",
        photo: "http://image.tmdb.org/t/p/w185/c7UPkmhIXYWmlqaQK250L8GTsPQ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 16,
        movie_id: 2,
        name: "Diane Guerrero",
        photo: "http://image.tmdb.org/t/p/w185/5LXvRYdxKLWROAD2KDSXzRNNSdE.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 17,
        movie_id: 3,
        name: "Christian Bale",
        photo: "http://image.tmdb.org/t/p/w185/qCpZn2e3dimwbryLnqxZuI88PTi.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 18,
        movie_id: 3,
        name: "Heath Ledger",
        photo: "http://image.tmdb.org/t/p/w185/5Y9HnYYa9jF4NunY9lSgJGjSe8E.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 19,
        movie_id: 3,
        name: "Michael Caine",
        photo: "http://image.tmdb.org/t/p/w185/hZruclwEPCKw3e83rnFSIH5sRFZ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 20,
        movie_id: 3,
        name: "Gary Oldman",
        photo: "http://image.tmdb.org/t/p/w185/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 21,
        movie_id: 3,
        name: "Aaron Eckhart",
        photo: "http://image.tmdb.org/t/p/w185/5EFQvRHlpP1Iaw2e6vjOaBny6DV.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 22,
        movie_id: 3,
        name: "Maggie Gyllenhaal",
        photo: "http://image.tmdb.org/t/p/w185/qxgM5LzzG4uWTprCL3gBVVJ2Q1K.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 23,
        movie_id: 3,
        name: "Morgan Freeman",
        photo: "http://image.tmdb.org/t/p/w185/oIciQWr8VwKoR8TmAw1owaiZFyb.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 24,
        movie_id: 3,
        name: "Nestor Carbonell",
        photo: "http://image.tmdb.org/t/p/w185/wAk4Me2INiNSpRvzU8K98743Uc1.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 31,
        movie_id: 4,
        name: "Rosalie Chiang",
        photo: "http://image.tmdb.org/t/p/w185/cbEWkQM0FS9vzv07JFErCk0YKkx.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 25,
        movie_id: 4,
        name: "Sandra Oh",
        photo: "http://image.tmdb.org/t/p/w185/zU8vjebHxcP60ESEL5Ok68KWZvj.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 26,
        movie_id: 4,
        name: "Ava Morse",
        photo: "http://image.tmdb.org/t/p/w185/e3bkf5MHPzqvSrJALr78pp0DCWt.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 27,
        movie_id: 4,
        name: "Hyein Park",
        photo: "http://image.tmdb.org/t/p/w185/aud7tBslfKn2qIrKCbltxpXoOTi.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 28,
        movie_id: 4,
        name: "Maitreyi Ramakrishnan",
        photo: "http://image.tmdb.org/t/p/w185/jBFqjwvngaz6ZXEhNd6dMeZ0W6c.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 29,
        movie_id: 4,
        name: "Orion Lee",
        photo: "http://image.tmdb.org/t/p/w185/glWRdpNnOj9JBmrbiCuvUWkBejf.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 30,
        movie_id: 4,
        name: "Wai Ching Ho",
        photo: "http://image.tmdb.org/t/p/w185/sbEwwkKVcLJRi02ZCqx8JymmbTm.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 32,
        movie_id: 4,
        name: "Tristan Allerick Chen",
        photo: "http://image.tmdb.org/t/p/w185/zFqLvvVEk4q8RgCDAKXxUahwZ7n.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 33,
        movie_id: 5,
        name: "Jared Leto",
        photo: "http://image.tmdb.org/t/p/w185/lZaE3x8yxofNZ96xpthxuVXQxTM.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 34,
        movie_id: 5,
        name: "Matt Smith",
        photo: "http://image.tmdb.org/t/p/w185/xr2GSp8Pm6fT5VGm0I9tsWVcZ8q.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 35,
        movie_id: 5,
        name: "Adria Arjona",
        photo: "http://image.tmdb.org/t/p/w185/2xAwAxrjZrgfyrNYToBIjg1ZeRB.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 36,
        movie_id: 5,
        name: "Jared Harris",
        photo: "http://image.tmdb.org/t/p/w185/jAyPWkmge3BqXtgxIG9MfXBzOGj.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 37,
        movie_id: 5,
        name: "Al Madrigal",
        photo: "http://image.tmdb.org/t/p/w185/p4vN80EGGlzLb5J7G8Ss3n9K2pc.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 38,
        movie_id: 5,
        name: "Tyrese Gibson",
        photo: "http://image.tmdb.org/t/p/w185/eHhIFk7HOElgFCaD4igtAgn41kA.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 39,
        movie_id: 5,
        name: "Michael Keaton",
        photo: "http://image.tmdb.org/t/p/w185/baeHNv3qrVsnApuKbZXiJOhqMnw.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 40,
        movie_id: 5,
        name: "Zaris-Angel Hator",
        photo: "",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 41,
        movie_id: 6,
        name: "Tom Holland",
        photo: "http://image.tmdb.org/t/p/w185/2qhIDp44cAqP2clOgt2afQI07X8.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 42,
        movie_id: 6,
        name: "Mark Wahlberg",
        photo: "http://image.tmdb.org/t/p/w185/bTEFpaWd7A6AZVWOqKKBWzKEUe8.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 43,
        movie_id: 6,
        name: "Sophia Ali",
        photo: "http://image.tmdb.org/t/p/w185/uqXn3Gp0FlsV5kDLwJ6FbeuJvx2.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 44,
        movie_id: 6,
        name: "Tati Gabrielle",
        photo: "http://image.tmdb.org/t/p/w185/txZTL1HkPVxliTilbjlwR51VIt6.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 45,
        movie_id: 6,
        name: "Antonio Banderas",
        photo: "http://image.tmdb.org/t/p/w185/iWIUEwgn2KW50MssR7tdPeFoRGW.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 46,
        movie_id: 6,
        name: "Steven Waddington",
        photo: "http://image.tmdb.org/t/p/w185/gmlX5NNJI5HoNrK3RUPwBUmUgBW.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 47,
        movie_id: 6,
        name: "Rudy Pankow",
        photo: "http://image.tmdb.org/t/p/w185/rnXgJZ6BJUlBGUzGtpVHNXZLbL.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 48,
        movie_id: 6,
        name: "Tiernan Jones",
        photo: "http://image.tmdb.org/t/p/w185/2F3XY7pxQ963YyBtTp6PLXg6bi6.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 49,
        movie_id: 7,
        name: "Jude Law",
        photo: "http://image.tmdb.org/t/p/w185/A6Y0m7qEe04ZTHKyYDLbnyCHNzn.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 50,
        movie_id: 7,
        name: "Eddie Redmayne",
        photo: "http://image.tmdb.org/t/p/w185/fSvG7qzoBBnJUmgtIuMgrK3EQPN.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 51,
        movie_id: 7,
        name: "Mads Mikkelsen",
        photo: "http://image.tmdb.org/t/p/w185/ntwPvV4GKGGHO3I7LcHMwhXfsw9.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 52,
        movie_id: 7,
        name: "Ezra Miller",
        photo: "http://image.tmdb.org/t/p/w185/6wmTpbYpmhthaxzM5ss3377F9IV.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 53,
        movie_id: 7,
        name: "Dan Fogler",
        photo: "http://image.tmdb.org/t/p/w185/zJWbLEjfbDthBMucq9M6L4GJXL3.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 54,
        movie_id: 7,
        name: "Alison Sudol",
        photo: "http://image.tmdb.org/t/p/w185/wGOsMx9abtewju66CgUmUYHpveU.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 55,
        movie_id: 7,
        name: "Callum Turner",
        photo: "http://image.tmdb.org/t/p/w185/hV8YXEJF2RkpOJIano3Dwn5V3dH.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 56,
        movie_id: 7,
        name: "Jessica Williams",
        photo: "http://image.tmdb.org/t/p/w185/n7fP2YluY2jmQPGbPWu3It1BNd.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },

      {
        id: 58,
        movie_id: 8,
        name: "James Marsden",
        photo: "http://image.tmdb.org/t/p/w185/mk142GG0saiSXALY6V4wWcmPROW.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 59,
        movie_id: 8,
        name: "Ben Schwartz",
        photo: "http://image.tmdb.org/t/p/w185/5vV52TSEIhe4ZZLWwv3i7nfv8we.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 60,
        movie_id: 8,
        name: "Tika Sumpter",
        photo: "http://image.tmdb.org/t/p/w185/6Hb9e7jna7nml58cztAvbKgFAPx.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 61,
        movie_id: 8,
        name: "Natasha Rothwell",
        photo: "http://image.tmdb.org/t/p/w185/x5KdL3QoS4YuozVpfuPsu3MLwwf.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 62,
        movie_id: 8,
        name: "Adam Pally",
        photo: "http://image.tmdb.org/t/p/w185/yY13PEaVbPoXT5MkitVxTfdAZnU.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 63,
        movie_id: 8,
        name: "Shemar Moore",
        photo: "http://image.tmdb.org/t/p/w185/hO9pskl1sgKkghjCTa1eHVv5OMN.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 64,
        movie_id: 8,
        name: "Colleen O'Shaughnessey",
        photo: "http://image.tmdb.org/t/p/w185/y3Kl5tCX1XD6uyL9wefTRbEXTwj.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 65,
        movie_id: 8,
        name: "Lee Majdoub",
        photo: "http://image.tmdb.org/t/p/w185/vpF3R2YRCGHseGevmDAhftmOPkO.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 66,
        movie_id: 9,
        name: "Sandra Bullock",
        photo: "http://image.tmdb.org/t/p/w185/u2tnZ0L2dwrzFKevVANYT5Pb1nE.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 67,
        movie_id: 9,
        name: "Channing Tatum",
        photo: "http://image.tmdb.org/t/p/w185/e5p1xrGtPfpJBQR9Pt3B6W4buZP.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 68,
        movie_id: 9,
        name: "Daniel Radcliffe",
        photo: "http://image.tmdb.org/t/p/w185/uAICvHxj4cwSGjEY9B09Mhqxrk.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 69,
        movie_id: 9,
        name: "Brad Pitt",
        photo: "http://image.tmdb.org/t/p/w185/cckcYc2v0yh1tc9QjRelptcOBko.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 70,
        movie_id: 9,
        name: "Da'Vine Joy Randolph",
        photo: "http://image.tmdb.org/t/p/w185/awNT6lltD8zItbGtolmO8IGT8ot.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 71,
        movie_id: 9,
        name: "Patti Harrison",
        photo: "http://image.tmdb.org/t/p/w185/xcTRN4vILwgFBiAKszes8qUaRuM.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 72,
        movie_id: 9,
        name: "Oscar Nunez",
        photo: "http://image.tmdb.org/t/p/w185/UBILHiRphJdlshvsyH920QSAhk.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 73,
        movie_id: 9,
        name: "Bowen Yang",
        photo: "http://image.tmdb.org/t/p/w185/jOqMWGWRIjRZBboV4XwCh6yLxva.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 74,
        movie_id: 10,
        name: "Chris Pratt",
        photo: "http://image.tmdb.org/t/p/w185/gXKyT1YU5RWWPaE1je3ht58eUZr.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 75,
        movie_id: 10,
        name: "Bryce Dallas Howard",
        photo: "http://image.tmdb.org/t/p/w185/qQX1rhQaJ1G8eMG2RknFKiXfNRc.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 76,
        movie_id: 10,
        name: "Laura Dern",
        photo: "http://image.tmdb.org/t/p/w185/gB9PnGEvxKg33OSlcqptQwTBwPE.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 77,
        movie_id: 10,
        name: "Jeff Goldblum",
        photo: "http://image.tmdb.org/t/p/w185/m8p62pvkVtPxkfAIJhb5AgGw8kA.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 78,
        movie_id: 10,
        name: "Sam Neill",
        photo: "http://image.tmdb.org/t/p/w185/bNZ03phkLewj8eUR6mGbKZ7jtmv.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 79,
        movie_id: 10,
        name: "DeWanda Wise",
        photo: "http://image.tmdb.org/t/p/w185/daQjduDoTzaDTC6SIsGWs55dzcM.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 80,
        movie_id: 10,
        name: "Mamoudou Athie",
        photo: "http://image.tmdb.org/t/p/w185/w12x0SI8acaWEKFid91UMgPyTZw.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 81,
        movie_id: 10,
        name: "Isabella Sermon",
        photo: "http://image.tmdb.org/t/p/w185/17lNC9C1mNuP0o5AJamwTJ9oaD5.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 82,
        movie_id: 11,
        name: "Liam Neeson",
        photo: "http://image.tmdb.org/t/p/w185/bboldwqSC6tdw2iL6631c98l2Mn.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 83,
        movie_id: 11,
        name: "Guy Pearce",
        photo: "http://image.tmdb.org/t/p/w185/vTqk6Nh3WgqPubkS23eOlMAwmwa.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 84,
        movie_id: 11,
        name: "Taj Atwal",
        photo: "http://image.tmdb.org/t/p/w185/gxWHVyNsctpLUOSfbTWjNXxgrDF.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 85,
        movie_id: 11,
        name: "Harold Torres",
        photo: "http://image.tmdb.org/t/p/w185/foIfRtugFwPzNYOhzKpsfb9zFXU.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 86,
        movie_id: 11,
        name: "Monica Bellucci",
        photo: "http://image.tmdb.org/t/p/w185/k0GJCAfBNCFKamJ56pBPk9gqhLy.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 87,
        movie_id: 11,
        name: "Ray Stevenson",
        photo: "http://image.tmdb.org/t/p/w185/msafbswGI6uisRuNvQ8a1wMF5Ca.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 88,
        movie_id: 11,
        name: "Stella Stocker",
        photo: "http://image.tmdb.org/t/p/w185/ilRVeYRcQrAeHYLMOPPzLzZMJcC.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 89,
        movie_id: 11,
        name: "Antonio Jaramillo",
        photo: "http://image.tmdb.org/t/p/w185/6xLThPXEOLPGxZ7Szi1X3cGRZ8g.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 90,
        movie_id: 12,
        name: "Alexander Skarsgård",
        photo: "http://image.tmdb.org/t/p/w185/caOe6hwHEE89AJfGdHatnrGgkKj.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 91,
        movie_id: 12,
        name: "Nicole Kidman",
        photo: "http://image.tmdb.org/t/p/w185/dlcNtb7y0Be1pOWdsogowLEsOta.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 92,
        movie_id: 12,
        name: "Claes Bang",
        photo: "http://image.tmdb.org/t/p/w185/zW6h8zD6vEcJdt10CJvP6fIHcBK.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 93,
        movie_id: 12,
        name: "Ethan Hawke",
        photo: "http://image.tmdb.org/t/p/w185/a7rgJl8TYUWAfJuM4fxbLHgD7BL.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 94,
        movie_id: 12,
        name: "Anya Taylor-Joy",
        photo: "http://image.tmdb.org/t/p/w185/aSOvCmB1nsl19IqrjuuWwaguvDh.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 95,
        movie_id: 12,
        name: "Willem Dafoe",
        photo: "http://image.tmdb.org/t/p/w185/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 96,
        movie_id: 12,
        name: "Björk",
        photo: "http://image.tmdb.org/t/p/w185/dDsLL1f2FfHfUDdIHmSkloxunnM.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 97,
        movie_id: 12,
        name: "Gustav Lindh",
        photo: "http://image.tmdb.org/t/p/w185/a92RvY2O8jn3MtNFi2dJMDr0NFc.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 98,
        movie_id: 13,
        name: "Benedict Cumberbatch",
        photo: "http://image.tmdb.org/t/p/w185/fBEucxECxGLKVHBznO0qHtCGiMO.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 99,
        movie_id: 13,
        name: "Elizabeth Olsen",
        photo: "http://image.tmdb.org/t/p/w185/7Gr7Gpwvn05pnsawfNAlob1PAK3.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 100,
        movie_id: 13,
        name: "Chiwetel Ejiofor",
        photo: "http://image.tmdb.org/t/p/w185/kq5DDnqqofoRI0t6ddtRlsJnNPT.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 101,
        movie_id: 13,
        name: "Benedict Wong",
        photo: "http://image.tmdb.org/t/p/w185/ukmfsl59Isvn9odgzMWBidA3cmt.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 102,
        movie_id: 13,
        name: "Xochitl Gomez",
        photo: "http://image.tmdb.org/t/p/w185/ssaMb4nWhtrcvRjPKubVrF0AeFO.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 103,
        movie_id: 13,
        name: "Jett Klyne",
        photo: "http://image.tmdb.org/t/p/w185/yrbY3ebII569deRr9NLD9kKV0HO.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 104,
        movie_id: 13,
        name: "Julian Hilliard",
        photo: "http://image.tmdb.org/t/p/w185/umnRZFm9pQ9xB53PQwUPFOVul4j.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 105,
        movie_id: 13,
        name: "Sheila Atim",
        photo: "http://image.tmdb.org/t/p/w185/vUNzuhGFT4SVeu5HqxKVU9eFCE.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 106,
        movie_id: 14,
        name: "Adrien Brody",
        photo: "http://image.tmdb.org/t/p/w185/1dBItgLFBNGEXnI48VvnnN2vFaX.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 107,
        movie_id: 14,
        name: "Glenn Fleshler",
        photo: "http://image.tmdb.org/t/p/w185/x1Cef2yPZS7bJTwxI7DX3q0HNcv.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 108,
        movie_id: 14,
        name: "Richie Merritt",
        photo: "http://image.tmdb.org/t/p/w185/9guamI0YrLggrGjVSth9OnUrhRQ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 109,
        movie_id: 14,
        name: "Chandler Ari DuPont",
        photo: "http://image.tmdb.org/t/p/w185/2afAVmJ19dTzDDKWMwwRBod4SbZ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 110,
        movie_id: 14,
        name: "Michelle Wilson",
        photo: "http://image.tmdb.org/t/p/w185/hwxFHlJyCrbcrtFRCFXdqAqcBPo.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 111,
        movie_id: 14,
        name: "John Bianco",
        photo: "http://image.tmdb.org/t/p/w185/28h0FT82uZBqfMGFOY3Ta2rSuCE.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 112,
        movie_id: 14,
        name: "Dinora Walcott",
        photo: "http://image.tmdb.org/t/p/w185/5TiaiBiciGqIs3QvRKHeHHFTmAj.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 113,
        movie_id: 14,
        name: "Mykelti Williamson",
        photo: "http://image.tmdb.org/t/p/w185/b68ZTxJL8EuvGMCcgSH3Mbn2GxP.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 114,
        movie_id: 15,
        name: "Robert Pattinson",
        photo: "http://image.tmdb.org/t/p/w185/6RVxNlNmc0DIfZzaJKCJM43If3M.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 115,
        movie_id: 15,
        name: "Zoë Kravitz",
        photo: "http://image.tmdb.org/t/p/w185/4uOfGQSKCz2I7HVV5vPwhvTD61y.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 116,
        movie_id: 15,
        name: "Paul Dano",
        photo: "http://image.tmdb.org/t/p/w185/tHsaqfauzG4MuFs5oCbq0pRy5EF.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 117,
        movie_id: 15,
        name: "Jeffrey Wright",
        photo: "http://image.tmdb.org/t/p/w185/npJjOiFiAP4wiRDNjKsO8ho03Mg.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 118,
        movie_id: 15,
        name: "John Turturro",
        photo: "http://image.tmdb.org/t/p/w185/6O9W9cJW0kCqMzYeLupV9oH0ftn.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 119,
        movie_id: 15,
        name: "Peter Sarsgaard",
        photo: "http://image.tmdb.org/t/p/w185/jOc4VjxPaOkWOqnLCxd8BJy9g5i.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 120,
        movie_id: 15,
        name: "Andy Serkis",
        photo: "http://image.tmdb.org/t/p/w185/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 121,
        movie_id: 15,
        name: "Colin Farrell",
        photo: "http://image.tmdb.org/t/p/w185/3iHqlaeSAQwJ0KraRKD1A4vBaCS.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 122,
        movie_id: 16,
        name: "Caterina Murino",
        photo: "http://image.tmdb.org/t/p/w185/qwCb6uM20i0sg8N4RZges97keUk.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 123,
        movie_id: 16,
        name: "Cosimo Fusco",
        photo: "http://image.tmdb.org/t/p/w185/tzlLC0hxVspwBTMVB7x6mAuhnXV.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 124,
        movie_id: 16,
        name: "Ingrid García Jonsson",
        photo: "http://image.tmdb.org/t/p/w185/gyv9JQOehJCHgtKzGq9FvLy3mSp.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 125,
        movie_id: 16,
        name: "Nico Romero",
        photo: "http://image.tmdb.org/t/p/w185/zK0zTAaCxbaoE3C0nKvkZOdwWu6.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 126,
        movie_id: 16,
        name: "Silvia Alonso",
        photo: "http://image.tmdb.org/t/p/w185/AgXsHxxSBOy9JmtWy5o8y3cKprY.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 127,
        movie_id: 16,
        name: "Enrico Lo Verso",
        photo: "http://image.tmdb.org/t/p/w185/riYINKQIv8mxYwtfj0L899K0iPu.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 128,
        movie_id: 16,
        name: "Armando De Razza",
        photo: "http://image.tmdb.org/t/p/w185/cc6jUaH7fTfcqASSmARdDUb0RaL.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 129,
        movie_id: 16,
        name: "Nicolás Illoro",
        photo: "http://image.tmdb.org/t/p/w185/gOPwiwZm5bfRlAiKog5S1FlipzB.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 130,
        movie_id: 17,
        name: "Kevin Dillon",
        photo: "http://image.tmdb.org/t/p/w185/tIadFMFzA6LcXaAaVpJmrd7waXQ.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 131,
        movie_id: 17,
        name: "Bruce Willis",
        photo: "http://image.tmdb.org/t/p/w185/caX3KtMU42EP3VLRFFBwqIIrch5.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 132,
        movie_id: 17,
        name: "Leon",
        photo: "http://image.tmdb.org/t/p/w185/uhLVZV2rH0nnXwQKtsIT0qGsTyg.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 133,
        movie_id: 17,
        name: "Frank Grillo",
        photo: "http://image.tmdb.org/t/p/w185/br2nPzelch2Tb3pZHnYAbXng7cz.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 134,
        movie_id: 17,
        name: "Gianni Capaldi",
        photo: "http://image.tmdb.org/t/p/w185/u4aBjxRSBNbn8OV8Sg23GnkBJbb.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 135,
        movie_id: 17,
        name: "Brooke Butler",
        photo: "http://image.tmdb.org/t/p/w185/d7ibZgYSHgoY1aMF5xMIBY6cJ8v.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 136,
        movie_id: 17,
        name: "Johnny Messner",
        photo: "http://image.tmdb.org/t/p/w185/1TL83UaGFeBg0Se3h9r066VcHjo.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 137,
        movie_id: 17,
        name: "Vernon Davis",
        photo: "http://image.tmdb.org/t/p/w185/dUyQ9pw2ZtqRLqH1F5fqwEgaExq.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 138,
        movie_id: 18,
        name: "Sam Rockwell",
        photo: "http://image.tmdb.org/t/p/w185/4zjUldl3ykbgcLO7FxWppR6s7Ck.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 139,
        movie_id: 18,
        name: "Marc Maron",
        photo: "http://image.tmdb.org/t/p/w185/2ENNRs7lgbyLfrUN622zRqkYJWL.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 140,
        movie_id: 18,
        name: "Awkwafina",
        photo: "http://image.tmdb.org/t/p/w185/l5AKkg3H1QhMuXmTTmq1EyjyiRb.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 141,
        movie_id: 18,
        name: "Craig Robinson",
        photo: "http://image.tmdb.org/t/p/w185/nWZI2ghokrha2lYnr5Z48agItL7.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 142,
        movie_id: 18,
        name: "Anthony Ramos",
        photo: "http://image.tmdb.org/t/p/w185/ityTHqIXFT3laID4j4ptlnc84zq.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 143,
        movie_id: 18,
        name: "Richard Ayoade",
        photo: "http://image.tmdb.org/t/p/w185/qHKoy9kP4bsv4G9EkvU4FMUmYkS.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 144,
        movie_id: 18,
        name: "Zazie Beetz",
        photo: "http://image.tmdb.org/t/p/w185/sgxzT54GnvgeMnOZgpQQx9csAdd.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 145,
        movie_id: 18,
        name: "Alex Borstein",
        photo: "http://image.tmdb.org/t/p/w185/evbCnRe5Yfuy0B41PONLTIcvbem.jpg",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("actors", null, {});
  },
};
